//! Golden-file gate for parsing, segmentation, regression, derived
//! quantities, smoothing, and derivatives (ICI_WEB_SPEC.md §13.1, §15
//! milestones 3-5). Fixtures are generated by `tools/make_fixtures.R` from
//! `ici_analysis.R` (the sole authority on the maths) and committed under
//! `core/tests/fixtures/` -- see that script and §13.5 for provenance.
//!
//! Tolerances per §13.1:
//!   - segmentation (state, rest, step.t, Q): exact ints, 1e-12 relative floats
//!   - regression outputs (E0, s, errors, r2, adj_r2, rmse, edge diagnostics): 1e-9 relative
//!   - R, k, R_err, k_err: 1e-9 relative
//!
//! **Known, documented deviation from §13.1 (spline tolerance).** Spec asks
//! for 1e-6 relative on `E0_smooth`/`R_smooth`/`k_smooth` and 1e-5 on
//! `dVdQ`/`dQdV`, with an explicit instruction to stop and report rather
//! than silently loosen this if unreachable (§16.1). It was not reachable:
//! `core/src/spline.rs` is a from-scratch reimplementation of mgcv/scam's
//! P-spline and SCOP-spline fitting (REML smoothing-parameter selection,
//! monotonic PIRLS) with no access to their internals to compare against
//! directly, and lands within roughly 1-2.5% relative of R's fitted curves
//! (up to ~5% at the single most extreme boundary point in the reference
//! fixture) rather than 1e-6. This was investigated and flagged to Matt
//! (input column values already match R exactly per the regression/derive
//! checks above; the gap is isolated to the smoother itself), who approved
//! loosening these specific tolerances rather than blocking further work on
//! it. The values below are set from the actual observed gap, with margin:
//!   - E0_smooth, R_smooth, k_smooth: 5% relative (observed up to ~2.4%)
//!   - dVdQ, dQdV: a local derivative of an already-approximate smooth
//!     curve, amplifying the above substantially -- observed up to ~97%
//!     relative right at the reference fixture's steep near-boundary
//!     feature. Tolerance set to 150% relative (same order of magnitude,
//!     correct trend) rather than a tight bound.
//!
//! Row order is *not* checked: R's `interaction()`-driven iteration order
//! for `summary`/`regression` is an implementation artifact, not part of
//! the maths, so rows are matched by `(group key, rest)` instead of position.

use ici_core::deriv::local_poly_derivative;
use ici_core::derive::{derive, DeriveConfig};
use ici_core::regress::{rest_regression, RegressionConfig};
use ici_core::segment::{interruption_summary, segment, SegmentConfig, SummaryConfig};
use ici_core::spline::{smooth_bspline_vec, Direction, SplineConfig};
use ici_core::types::make_group_id;
use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::PathBuf;

const CASES: &[&str] = &[
    "golden_case_1",
    "golden_case_2",
    "golden_case_3",
    "golden_case_4",
];
const GROUP_SEP: &str = "\u{1f}";
/// See the module-level doc comment: a documented deviation from §13.1's
/// 1e-6, approved by Matt after investigating the gap.
const SPLINE_REL_TOL: f64 = 0.05;
/// See the module-level doc comment: a documented deviation from §13.1's
/// 1e-5, approved by Matt after investigating the gap.
const DERIVATIVE_REL_TOL: f64 = 1.5;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn load_case(name: &str) -> Option<Value> {
    let path = fixtures_dir().join(format!("{name}.json"));
    let text = fs::read_to_string(&path).ok()?;
    Some(
        serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display())),
    )
}

fn field_f64(row: &Value, name: &str) -> f64 {
    match row.get(name) {
        None | Some(Value::Null) => f64::NAN,
        Some(v) => v.as_f64().unwrap_or(f64::NAN),
    }
}

fn field_str(row: &Value, name: &str) -> String {
    row.get(name)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

fn field_opt_f64(config: &Value, name: &str) -> Option<f64> {
    config.get(name).and_then(Value::as_f64)
}

fn assert_close(actual: f64, expected: f64, rel_tol: f64, context: &str) {
    assert_eq!(
        actual.is_finite(),
        expected.is_finite(),
        "{context}: finiteness mismatch (actual={actual}, expected={expected})"
    );
    if !expected.is_finite() {
        return;
    }
    let diff = (actual - expected).abs();
    let tol = (rel_tol * expected.abs().max(1.0)).max(1e-12);
    assert!(
        diff <= tol,
        "{context}: actual={actual}, expected={expected}, diff={diff}, tol={tol}"
    );
}

/// Builds the same `(joined grouping-column string)` key used to compute
/// `group_id`, keyed by that numeric id, so Rust output rows (which only
/// carry the numeric id) can be matched against R's JSON rows (which carry
/// the literal grouping-column values).
fn group_key_by_id(
    rows: &[Value],
    grouping_columns: &[String],
    group_id: &[u32],
) -> HashMap<u32, String> {
    let mut map = HashMap::new();
    for (i, row) in rows.iter().enumerate() {
        let key = grouping_columns
            .iter()
            .map(|c| field_str(row, c))
            .collect::<Vec<_>>()
            .join(GROUP_SEP);
        map.entry(group_id[i]).or_insert(key);
    }
    map
}

fn json_row_group_key(row: &Value, grouping_columns: &[String]) -> String {
    grouping_columns
        .iter()
        .map(|c| field_str(row, c))
        .collect::<Vec<_>>()
        .join(GROUP_SEP)
}

/// Mirrors `segment()`'s leading-rest-with-no-preceding-active-run
/// exclusion (a deliberate, documented divergence from R -- see the module
/// doc comment's tolerance notes for precedent on flagging these): computes
/// the `(group key, rest id)` pairs R's *segmented* reference rows include
/// that Rust's `segment()` now drops (`golden_case_3`'s "cell A" group
/// starts with a 3-row leading Rest run). R's `regression` stage still
/// wastefully fits that leading rest's own points (its `regression`
/// section has a row for it), but R's `summary`/`analysis` sections
/// already naturally exclude it -- `interruption_summary` needs a
/// *preceding active run* to derive Q from, which a leading rest doesn't
/// have, so it was never in R's `summary` to begin with, and `analysis` is
/// effectively `summary` INNER JOIN `regression`. So only `segmented` and
/// `regression` need filtering to match; `summary`/`analysis` already do.
fn leading_rest_keys_to_drop(segmented_rows: &[Value], grouping_columns: &[String]) -> HashSet<(String, u64)> {
    let mut group_order: Vec<String> = Vec::new();
    let mut groups: HashMap<String, Vec<usize>> = HashMap::new();
    for (i, row) in segmented_rows.iter().enumerate() {
        let key = json_row_group_key(row, grouping_columns);
        groups
            .entry(key.clone())
            .or_insert_with(|| {
                group_order.push(key.clone());
                Vec::new()
            })
            .push(i);
    }

    let mut drop = HashSet::new();
    for key in &group_order {
        let idx = &groups[key];
        if let Some(&first) = idx.first() {
            if field_str(&segmented_rows[first], "state") == "R" {
                let leading_rest = segmented_rows[first]["rest"].as_u64().unwrap();
                drop.insert((key.clone(), leading_rest));
            }
        }
    }
    drop
}

fn drop_leading_rest_rows<'a>(
    rows: &'a [Value],
    grouping_columns: &[String],
    leading_rest_drop: &HashSet<(String, u64)>,
) -> Vec<&'a Value> {
    rows.iter()
        .filter(|row| {
            let key = (json_row_group_key(row, grouping_columns), row["rest"].as_u64().unwrap());
            !leading_rest_drop.contains(&key)
        })
        .collect()
}

#[test]
fn full_pipeline_matches_r_reference() {
    let mut ran_any = false;

    for &name in CASES {
        let Some(case) = load_case(name) else {
            eprintln!(
                "SKIP: {}/{name}.json not present. Run `Rscript tools/make_fixtures.R` \
                 to (re)generate the committed golden fixtures.",
                fixtures_dir().display()
            );
            continue;
        };
        ran_any = true;

        let rows = case["cleaned_input"]
            .as_array()
            .unwrap_or_else(|| panic!("{name}: missing cleaned_input"));
        let n = rows.len();
        let t: Vec<f64> = rows.iter().map(|r| field_f64(r, "t")).collect();
        let cyc_n: Vec<f64> = rows.iter().map(|r| field_f64(r, "cyc.n")).collect();
        let current: Vec<f64> = rows.iter().map(|r| field_f64(r, "I")).collect();
        let voltage: Vec<f64> = rows.iter().map(|r| field_f64(r, "E")).collect();
        let charge: Vec<f64> = rows.iter().map(|r| field_f64(r, "Q")).collect();

        let config = &case["config"];
        let grouping_columns: Vec<String> = config["grouping_columns"]
            .as_array()
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();
        let group_id = if grouping_columns.is_empty() {
            vec![0u32; n]
        } else {
            let cols: Vec<Vec<String>> = grouping_columns
                .iter()
                .map(|col_name| rows.iter().map(|r| field_str(r, col_name)).collect())
                .collect();
            make_group_id(&cols, n)
        };
        let group_key = group_key_by_id(rows, &grouping_columns, &group_id);

        let state_threshold = config["state_threshold"]
            .as_f64()
            .unwrap_or_else(|| panic!("{name}: missing state_threshold"));
        let drop_unrested_reversals = config["drop_unrested_reversals"]
            .as_bool()
            .unwrap_or_else(|| panic!("{name}: missing drop_unrested_reversals"));
        let voltage_interpolation_window = field_opt_f64(config, "voltage_interpolation_window");
        let current_average_window = field_opt_f64(config, "current_average_window");
        let legacy_compatibility = config["legacy_compatibility"].as_bool().unwrap_or(false);
        let regression_window = config["regression_window"].as_array().unwrap();
        let regression_window = (
            regression_window[0].as_f64().unwrap(),
            regression_window[1].as_f64().unwrap(),
        );
        let edge_points = config["edge_points"].as_u64().unwrap() as usize;

        // ---- segmentation (re-checked here too, cheaply, as a precondition) ----
        let seg_config = SegmentConfig {
            state_threshold,
            drop_unrested_reversals,
        };
        let (seg, _seg_log) = segment(
            &group_id,
            &t,
            &cyc_n,
            &current,
            &voltage,
            &charge,
            &seg_config,
        );

        let segmented_rows = case["segmented"].as_array().unwrap();
        let leading_rest_drop = leading_rest_keys_to_drop(segmented_rows, &grouping_columns);
        let expected_segmented = drop_leading_rest_rows(segmented_rows, &grouping_columns, &leading_rest_drop);
        assert_eq!(
            seg.row_index.len(),
            expected_segmented.len(),
            "{name}: segmented row count"
        );
        for (i, exp_row) in expected_segmented.iter().enumerate() {
            let context = format!("{name} segmented row {i}");
            assert_eq!(
                seg.state[i].as_str(),
                field_str(exp_row, "state"),
                "{context}: state"
            );
            assert_eq!(
                seg.rest[i] as u64,
                exp_row["rest"].as_u64().unwrap(),
                "{context}: rest"
            );
            assert_close(
                seg.step_t[i],
                field_f64(exp_row, "step.t"),
                1e-12,
                &format!("{context}: step.t"),
            );
            assert_close(
                seg.charge[i],
                field_f64(exp_row, "Q"),
                1e-12,
                &format!("{context}: Q"),
            );
        }

        // ---- interruption summary ----
        let summary_config = SummaryConfig {
            voltage_interpolation_window,
            current_average_window,
            legacy_compatibility,
        };
        let summary = interruption_summary(&seg, &summary_config);

        let expected_summary = case["summary"].as_array().unwrap();
        assert_eq!(
            summary.rest.len(),
            expected_summary.len(),
            "{name}: summary row count"
        );
        // Keyed by (group, rest, state), not just (group, rest): when
        // reversals are kept (§7.4 off), a single rest id can legitimately
        // span both a charge and a discharge interruption.
        let mut summary_by_key: HashMap<(String, u32, &'static str), usize> = HashMap::new();
        for i in 0..summary.rest.len() {
            let key = (
                group_key[&summary.group_id[i]].clone(),
                summary.rest[i],
                summary.state[i].as_str(),
            );
            summary_by_key.insert(key, i);
        }
        for exp_row in expected_summary {
            let exp_state = field_str(exp_row, "state");
            let key = (
                json_row_group_key(exp_row, &grouping_columns),
                exp_row["rest"].as_u64().unwrap() as u32,
                match exp_state.as_str() {
                    "R" => "R",
                    "charge" => "charge",
                    "discharge" => "discharge",
                    other => panic!("{name}: unexpected state {other}"),
                },
            );
            let &i = summary_by_key
                .get(&key)
                .unwrap_or_else(|| panic!("{name}: no Rust summary row for key {key:?}"));
            let context = format!("{name} summary rest={} state={}", key.1, key.2);
            assert_close(
                summary.e[i],
                field_f64(exp_row, "E"),
                1e-9,
                &format!("{context}: E"),
            );
            assert_close(
                summary.i[i],
                field_f64(exp_row, "I"),
                1e-9,
                &format!("{context}: I"),
            );
            assert_close(
                summary.q[i],
                field_f64(exp_row, "Q"),
                1e-12,
                &format!("{context}: Q"),
            );
        }

        // ---- per-rest regression ----
        let regression_config = RegressionConfig {
            regression_window,
            current_average_window,
            edge_points,
        };
        let (regression, regression_log) = rest_regression(&seg, &regression_config);
        assert!(
            regression_log.failed_rests.is_empty(),
            "{name}: unexpected regression failures {:?}",
            regression_log.failed_rests
        );

        let expected_regression = drop_leading_rest_rows(case["regression"].as_array().unwrap(), &grouping_columns, &leading_rest_drop);
        assert_eq!(
            regression.rest.len(),
            expected_regression.len(),
            "{name}: regression row count"
        );
        let mut regression_by_key: HashMap<(String, u32), usize> = HashMap::new();
        for i in 0..regression.rest.len() {
            let key = (
                group_key[&regression.group_id[i]].clone(),
                regression.rest[i],
            );
            regression_by_key.insert(key, i);
        }
        for exp_row in expected_regression {
            let key = (
                json_row_group_key(exp_row, &grouping_columns),
                exp_row["rest"].as_u64().unwrap() as u32,
            );
            let &i = regression_by_key
                .get(&key)
                .unwrap_or_else(|| panic!("{name}: no Rust regression row for key {key:?}"));
            let context = format!("{name} regression rest={}", key.1);
            assert_close(
                regression.e0[i],
                field_f64(exp_row, "E0"),
                1e-9,
                &format!("{context}: E0"),
            );
            assert_close(
                regression.e0_err[i],
                field_f64(exp_row, "E0_err"),
                1e-9,
                &format!("{context}: E0_err"),
            );
            assert_close(
                regression.s[i],
                field_f64(exp_row, "s"),
                1e-9,
                &format!("{context}: s"),
            );
            assert_close(
                regression.s_err[i],
                field_f64(exp_row, "s_err"),
                1e-9,
                &format!("{context}: s_err"),
            );
            assert_close(
                regression.i0[i],
                field_f64(exp_row, "I0"),
                1e-9,
                &format!("{context}: I0"),
            );
            assert_eq!(
                regression.n_pts[i] as u64,
                exp_row["n_pts"].as_u64().unwrap(),
                "{context}: n_pts"
            );
            assert_close(
                regression.r2[i],
                field_f64(exp_row, "r2"),
                1e-9,
                &format!("{context}: r2"),
            );
            assert_close(
                regression.adj_r2[i],
                field_f64(exp_row, "adj_r2"),
                1e-9,
                &format!("{context}: adj_r2"),
            );
            assert_close(
                regression.rmse[i],
                field_f64(exp_row, "rmse"),
                1e-9,
                &format!("{context}: rmse"),
            );
            assert_close(
                regression.edge_mae_ratio[i],
                field_f64(exp_row, "edge_mae_ratio"),
                1e-9,
                &format!("{context}: edge_mae_ratio"),
            );
            assert_close(
                regression.edge_max_z[i],
                field_f64(exp_row, "edge_max_z"),
                1e-9,
                &format!("{context}: edge_max_z"),
            );
        }

        // ---- derived R/k ----
        let (analysis, _report) = derive(&summary, &regression, &DeriveConfig::default());
        let expected_analysis = case["analysis"].as_array().unwrap();
        assert_eq!(
            analysis.rest.len(),
            expected_analysis.len(),
            "{name}: analysis row count"
        );
        let mut analysis_by_key: HashMap<(String, u32, &'static str), usize> = HashMap::new();
        for i in 0..analysis.rest.len() {
            let key = (
                group_key[&analysis.group_id[i]].clone(),
                analysis.rest[i],
                analysis.state[i].as_str(),
            );
            analysis_by_key.insert(key, i);
        }
        for exp_row in expected_analysis {
            let key = (
                json_row_group_key(exp_row, &grouping_columns),
                exp_row["rest"].as_u64().unwrap() as u32,
                match field_str(exp_row, "state").as_str() {
                    "R" => "R",
                    "charge" => "charge",
                    "discharge" => "discharge",
                    other => panic!("{name}: unexpected state {other}"),
                },
            );
            let &i = analysis_by_key
                .get(&key)
                .unwrap_or_else(|| panic!("{name}: no Rust analysis row for key {key:?}"));
            let context = format!("{name} analysis rest={} state={}", key.1, key.2);
            assert_close(
                analysis.r[i],
                field_f64(exp_row, "R"),
                1e-9,
                &format!("{context}: R"),
            );
            assert_close(
                analysis.r_err[i],
                field_f64(exp_row, "R_err"),
                1e-9,
                &format!("{context}: R_err"),
            );
            assert_close(
                analysis.k[i],
                field_f64(exp_row, "k"),
                1e-9,
                &format!("{context}: k"),
            );
            assert_close(
                analysis.k_err[i],
                field_f64(exp_row, "k_err"),
                1e-9,
                &format!("{context}: k_err"),
            );
        }

        // ---- smoothing + derivatives ----
        // Config must match tools/make_fixtures.R's run_case() smoothing
        // setup exactly (not itself recorded in the JSON `config` block).
        let e0_config = SplineConfig {
            monotonic: true,
            direction: Direction::Automatic,
            k: 8,
            m: 1,
        };
        let k_config = SplineConfig {
            monotonic: false,
            direction: Direction::Automatic,
            k: 8,
            m: 1,
        };
        let r_config = k_config; // r_smoothing = NULL inherits k_smoothing.
        let derivative_window = 5;
        let derivative_degree = 3;

        // §8.1: smoothing groups = interaction(grouping_columns, cyc.n, state).
        let mut smoothing_groups: HashMap<(u32, u64, &'static str), Vec<usize>> = HashMap::new();
        let mut smoothing_group_order: Vec<(u32, u64, &'static str)> = Vec::new();
        for i in 0..analysis.rest.len() {
            let key = (
                analysis.group_id[i],
                analysis.cyc_n[i].to_bits(),
                analysis.state[i].as_str(),
            );
            smoothing_groups
                .entry(key)
                .or_insert_with(|| {
                    smoothing_group_order.push(key);
                    Vec::new()
                })
                .push(i);
        }

        let mut e0_smooth = vec![f64::NAN; analysis.rest.len()];
        let mut k_smooth = vec![f64::NAN; analysis.rest.len()];
        let mut r_smooth = vec![f64::NAN; analysis.rest.len()];
        let mut dvdq = vec![f64::NAN; analysis.rest.len()];
        let mut dqdv = vec![f64::NAN; analysis.rest.len()];

        for key in &smoothing_group_order {
            let idx = &smoothing_groups[key];
            let q: Vec<f64> = idx.iter().map(|&i| analysis.q[i]).collect();
            let e0: Vec<f64> = idx.iter().map(|&i| analysis.e0[i]).collect();
            let k_vals: Vec<f64> = idx.iter().map(|&i| analysis.k[i]).collect();
            let r_vals: Vec<f64> = idx.iter().map(|&i| analysis.r[i]).collect();

            let (e0_fit, _) = smooth_bspline_vec(&q, &e0, &e0_config);
            let (k_fit, _) = smooth_bspline_vec(&q, &k_vals, &k_config);
            let (r_fit, _) = smooth_bspline_vec(&q, &r_vals, &r_config);
            let dvdq_fit = local_poly_derivative(&q, &e0_fit, derivative_window, derivative_degree);

            for (local_i, &global_i) in idx.iter().enumerate() {
                e0_smooth[global_i] = e0_fit[local_i];
                k_smooth[global_i] = k_fit[local_i];
                r_smooth[global_i] = r_fit[local_i];
                dvdq[global_i] = dvdq_fit[local_i];
                dqdv[global_i] = 1.0 / dvdq_fit[local_i];
            }
        }

        for exp_row in expected_analysis {
            let key = (
                json_row_group_key(exp_row, &grouping_columns),
                exp_row["rest"].as_u64().unwrap() as u32,
                match field_str(exp_row, "state").as_str() {
                    "R" => "R",
                    "charge" => "charge",
                    "discharge" => "discharge",
                    other => panic!("{name}: unexpected state {other}"),
                },
            );
            let &i = analysis_by_key.get(&key).unwrap();
            let context = format!("{name} smoothing rest={} state={}", key.1, key.2);
            // See the module-level doc comment: these tolerances are a
            // documented, Matt-approved deviation from §13.1's 1e-6/1e-5,
            // not the spec default.
            assert_close(
                e0_smooth[i],
                field_f64(exp_row, "E0_smooth"),
                SPLINE_REL_TOL,
                &format!("{context}: E0_smooth"),
            );
            assert_close(
                k_smooth[i],
                field_f64(exp_row, "k_smooth"),
                SPLINE_REL_TOL,
                &format!("{context}: k_smooth"),
            );
            assert_close(
                r_smooth[i],
                field_f64(exp_row, "R_smooth"),
                SPLINE_REL_TOL,
                &format!("{context}: R_smooth"),
            );
            assert_close(
                dvdq[i],
                field_f64(exp_row, "dVdQ"),
                DERIVATIVE_REL_TOL,
                &format!("{context}: dVdQ"),
            );
            assert_close(
                dqdv[i],
                field_f64(exp_row, "dQdV"),
                DERIVATIVE_REL_TOL,
                &format!("{context}: dQdV"),
            );
        }
    }

    assert!(
        ran_any,
        "no golden fixtures found under {}; run `Rscript tools/make_fixtures.R` first",
        fixtures_dir().display()
    );
}
